/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pedeja;

/**
 *
 * @author Eliseu
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadProdutos = new javax.swing.JMenuItem();
        Pedidos = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        menuVendasHistorico = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("PEDE JÁ LANCHONETE");
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setEnabled(false);

        Cadastros.setText("Cadastros");

        menuCadCliente.setText("Cliente");
        menuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClienteActionPerformed(evt);
            }
        });
        Cadastros.add(menuCadCliente);

        menuCadProdutos.setText("Produto");
        menuCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutosActionPerformed(evt);
            }
        });
        Cadastros.add(menuCadProdutos);

        jMenuBar1.add(Cadastros);

        Pedidos.setText("Pedidos");

        menuPedido.setText("Pedido");
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        Pedidos.add(menuPedido);

        jMenuBar1.add(Pedidos);

        Vendas.setText("Vendas");

        menuVendasHistorico.setText("Historico");
        menuVendasHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasHistoricoActionPerformed(evt);
            }
        });
        Vendas.add(menuVendasHistorico);

        jMenuBar1.add(Vendas);

        Clientes.setText("Clientes");

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        Clientes.add(menuClientes);

        jMenuBar1.add(Clientes);

        Produtos.setText("Produtos");

        menuProduto.setText("Produto");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        Produtos.add(menuProduto);

        jMenuBar1.add(Produtos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(794, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClienteActionPerformed
        // TODO add your handling code here:
        frmCadCliente cadCliente = new frmCadCliente();
        cadCliente.setVisible(true);
        
    }//GEN-LAST:event_menuCadClienteActionPerformed

    private void menuCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutosActionPerformed
        // TODO add your handling code here:
        frmCadProduto cadProduto = new frmCadProduto();
        cadProduto.setVisible(true);
    }//GEN-LAST:event_menuCadProdutosActionPerformed

    private void menuVendasHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasHistoricoActionPerformed
        // TODO add your handling code here:
        frmHistorico historico = new frmHistorico();
        historico.setVisible(true);
    }//GEN-LAST:event_menuVendasHistoricoActionPerformed

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
        // TODO add your handling code here:
        frmPedido pedido = new frmPedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_menuPedidoActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        // TODO add your handling code here:
        frmClientes clientes = new frmClientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        // TODO add your handling code here:
        frmProdutos produto = new frmProdutos();
        produto.setVisible(true);
    }//GEN-LAST:event_menuProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Pedidos;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuVendasHistorico;
    // End of variables declaration//GEN-END:variables
}
